[profile.default]
src = 'src'
out = 'out'
libraries = []
libs = ['lib']
remappings = [
  'forge-std/=lib/forge-std/src/'
]
optimizer = true
optimizer_runs = 200
solc = '0.8.20'

[fmt]
line_length = 100
